### ISSUE TITLE
Lejátszási listád (Watchlist) kategória hozzáadása

### ISSUE THREAD

**Issue by sorin-pop** [billsuxx/plugin.video.hbogohu#1]
Szia,

Észrevettem, hogy nincs ilyen kategória kilistázva, pedig tök jó, és hasznos/logikus, lenne. Hozzá tudod ezt valahogy adni?

(Kicsit utánanéztem a kódban, úgy tűnik a http://huapi.hbogo.eu/player50.svc/Groups/json/HUN/COMP/ API-t hívod ahhoz, hogy a kategóriákat listázd, és úgy tűnik az tényleg nem tartalmazza ezt a kategóriát. Nem tudom mennyire lehet ezen segíteni, szinte semmi infót nem találtam hbogo API-król...de valahogyan talán csak lehet...végülis fontos kategória, meg a honlapon is megjelenítik)

Előre is köszönöm, ha utána nézel.

Üdv.

**Comment by bolint** [comment]
A Watchlist nincs a kategóriák között, ez személyes beállítás.
A `https://huapi.hbogo.eu/v7/Settings/json/HUN/COMP`-ra kell ráhívni, a válazból menteni a `FavoritesGroupId`-t, majd ráhívni megfelelő (de ahogy látom már összeállított) headerekkel a `https://huapi.hbogo.eu/v7/CustomerGroup/json/HUN/COMP/[FavoritesGroupId]/-/-/-/1000/-/-/false` URL-re.
Nagyon szívesen beleraknám ezt, de OpenElec-en tudom tesztelni. Windows-os Kodival simán megy a plugin, van bejáratott teszt flow, hogy ne hagyjak valamit ki?

**Comment by billsuxx** [comment]
Hello,

időközben már én túladtam a raspberryn, szóval én is csak desktop (linux) alatt fogom tudni tesztelni, ha úgy látod hogy jó, tedd fel a pullrequestet, ahol tudom kipróbálom. Ha nem jó, majd visítanak :)

Udv,

**Comment by bolint** [comment]
Köszi, akkor megpróbálkozok ezzel. :)

**Comment by sorin-pop** [comment]
Koszi szepen sracok! En raspberry Pi-n hasznalom, tehat en majd ki tudom tesztelni ott.

**Comment by mkoree** [comment]
Köszi, ez a feature nekem is hasznos lenne. :) Én is tudom Raspberry Pi-n tesztelni, ha kell.

**Comment by bolint** [comment]
@billsuxx az `addon.xml`-be is frissíthetek (disclaimer magyarul, news csere az új menüpontra) vagy ezeket Te tartod karban?

**Comment by billsuxx** [comment]
Nyugodtan irj bele az addon.xml-be is.

**Comment by sorin-pop** [comment]
Sziasztok,

Kiteszteltem Bálint módositásait a Raspberry Pi-omon. Úgy tűnik működik szépen. Úgyhogy szerintem ez jöhet official release-ben is ki majd, hogy mindenkinek elérhető legyen ez a tök jó kis feature.

Köszönöm szépen Bálint, Dávid!

**Comment by hotelsinus** [comment]
sziasztok, várható ez az update?

**Comment by hotelsinus** [comment]
Hello, leszedtem a favorites változtatást és updateltem nvidia Shield TV-n , hibátélanul működik.

**Comment by billsuxx** [comment]
Bocsi a keslekedesert, kint van a friss verzio, bemergeltem a 2 pull requestet. 

Nagy koszonet mindenkinek.
