### ISSUE TITLE
Lejátszás probléma

### ISSUE THREAD

**Issue by mkoree** [billsuxx/plugin.video.hbogohu#4]
Hello,

Raspberry Pi-n használom a plugint, de az utóbbi pár hét óta nem működik nálam a lejátszás. Kiválasztom a megtekintendő elemet, rákattintok, bejön a spinner, kis időre eltűnik, majd megint visszajön, utána pedig visszadob abba a listába, ahonnan indítottam volna a lejátszást. A videó még csak a háttérben sem indul el. A logot böngészve az alábbit találtam, egyrészt az InputStream Adaptive panaszkodik a licensz szerverre, illetve az egész egy "ERROR: GetDirectory - Error getting"-el kezdődik, ezt sajnos nem tudom honnan jön. A felhasználónév/jelszó páros stimmel, ha ez nem lenne jó, akkor már a megtekinthető elemeket se látnám a listában, illetve a HBO GO oldalán is látom, hogy az eszköz beregisztrálja magát "Chromium 62" néven.

Bármilyen ötletet, segítséget szívesen látok, alább bemásoltam a teljes logot.

Köszi,
Kornél

> 18:58:43.840 T:1811604352   ERROR: GetDirectory - Error getting
> 18:58:58.844 T:1941346912   ERROR: Previous line repeats 6 times.
> 18:58:58.844 T:1941346912  NOTICE: VideoPlayer::OpenFile: https://level3cdn.hbogo.eu/f90bc034-77b6-d58d-c854-b989ad44c25e_hbo/COMP/24016707_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_3400000.ism/Manifest
> 18:58:58.896 T:1531794304  NOTICE: Creating InputStream
> 18:59:00.752 T:1531794304   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 406
> 18:59:00.754 T:1531794304   ERROR: CCurlFile::Open failed with code 406 for https://lic.drmtoday.com/license-proxy-widevine/cenc/|Content-Type&Expect&Origin=https%3a%2f%2fwww.hbogo.hu&acceptencoding=gzip%2c%20deflate&dt-custom-data=eyJ1c2VySWQiOiI0MDQ2MDZhMS1mNmMxLTRjNTItYmNjNC1hNmNlNGVlY2M4ZTciLCJzZXNzaW9uSWQiOiIyMWNkMzQ5Ny1hODMxLTRmMjctOWFmYi1mY2RkNjg4ZmI5NWEiLCJtZXJjaGFudCI6Imhib2V1cm9wZSJ9&postdata=CAESsQsK5goIARLxCQq0AggCEhZDaHJvbWVDRE0tQ2hyb21lT1MtQVJNGIOnjo4FIo4CMIIBCgKCAQEAsDzo%2bs1OMbZGG9XLnUcAbWMrn8nJ%2bZT%2f%2bmwUdgw8cZ1HXRKiz%2fikZDkcyD4dMUJ3bjxPXp20FcwRzoPc7wQwmX0r7Hu%2fAkMOJE5x0%2f7rIgNME1bX4BF4jvnxy9XV%2fzl9k5%2fsAXuE7DmBw11JW57VoclFawW8R3f6C7j6jmntRdT%2fvjZQjW8c3xYZBfIUyNXTxPpjj%2bak4Tag%2fOZe%2bo7eUi3029%2f8SVPH2GYWz5%2b3%2bKs2a9VlEC9vvMU60x3Lj7FP8aN835PoLcBRJVj5zHpm6GouI4YjGovnqmwkkinK8ohLDZVi1Zvq4wyp%2fc54qsxDzlAg7k467yzMyjE3gsWngQIDAQABKMYgEoACucqMKVKOLDtryRtyUSInJfLm0jvMHPkKc7aSXYFpqGDIxVZE3a8GAGaO66JCEXTA6%2fllCrfRoXxqN6MF49pIBtbo9fGrb2IBeVFkdki12vD8tp%2fL3QMOq21ajd7CdHDY2%2bighodev47nLpLS6hi1ju6wlSsa%2b3TOtlDMYDCsN%2ff7UZ73W8%2fIIcnWA%2bFwQlgXVfDL3ugKu8ox%2bbAkjCxknncBRpmloqssz%2fxHqTDDvIWWSsRMPMdSOz%2bfnJQEKD2H%2bJocrOKgY8NXq%2b8otI9wGPcrUX2WGF8PxnvqilHRL2eZ2lp%2bS9eecQkEXZLGbGTZoP2N%2fv7NHHY5LxA6fAVZvRq0BQquAggBEhAcpx1ZtWZFgxSev3rSMoVEGJ2jjo4FIo4CMIIBCgKCAQEAyeoN9jjxNASFTiPyJymuFXSNkVeamh9Hzo31ofd1ROv%2f40hoc5M0V0rog0yCIRLz7WSuGCK6rrUgHRx%2fTEi7nIgeH5AhVVAjIJ9oHScsJgExrhWkjcOTU1mxhBeUBvPxUMYB912VKnZszV652zYjqMVCUCiv9OIFvqhCU7XFqvWzo31ki70eCOGshmT7uYLmzkFwixxJ6%2fdgO4cBNbMIzSlAXqCCzk3%2briYu1nTqGXxFByGZ3x32lgD0rYO0kDSgHGW%2bvnXkCrMeLog37gdzcguPffjxZrmTm1UIvBhiOovPqHqZlGFyJtt1Kv9aTKoSYhu5I78FoMSecqvye%2fkMzQIDAQABKMYgEoADELzBNMGbeoR5XwyjUXoClZ8gCCEgUO2jxjzOfIBuC7NlNE9mH%2flxv5KUduYoyT9AIqCd7%2bZd1Y7S46dsEQMaxtHTyiQXqq8PXLL0kFZi5KLgdVRFLYsBQHYfx3TnZCfo86B6blVwvfpQWq09FDNGbF7rYMx%2bPb78ljoJlTXDF2As%2fuzmNhHnKju8p6Y4qM42W7sit7pdkcqCCCbukSULLHGcXwYJnvT9BQsx5rPkewEAKA0g0dtF3xXXd8NBunT0hVP77f3F5PTAkdSwcb7dDcsB%2bMvcQdLYSMkrU6GMOT3cRMqkFEryx8zbfVAhQ8I%2bYcbPsQfrMqYA39L5LvY61MSAzG9XNfbdjPKPzcE5l%2fwbGQ1U3c0VT5NsQpkP%2blyz%2bIP8lfUqTXxpLur76M8rEzUc94s3sWUFrKiXoWr7sGaEM9L8L2zTlFjstw8z%2fCtrQUtzzA2Tjf5Ocm0wYVMWUoUGCr3F%2b6ulLCUj3MWPHNwMSNle%2bXIEkEUtdBlAMOsfGhgKEWFyY2hpdGVjdHVyZV9uYW1lEgNhcm0aFgoMY29tcGFueV9uYW1lEgZHb29nbGUaFwoKbW9kZWxfbmFtZRIJQ2hyb21lQ0RNGhkKDXBsYXRmb3JtX25hbWUSCENocm9tZU9TMggIABAAGAAgARI8CjoKJBIQYWHC9ocWuTVBA%2bwUG4GhMCIQZmtqM2xqYVNkZmFsa3IzahABGhBAxUe3rgdIXTz6gHWQLXiVGAEg1IL%2b3QUwFRqAAofGhuRWRd67kuZ1Yw6Cw7elxmgGRROsHMrGaUaoD3O%2b%2fjN8uTKiYjZgYpgTCaLn%2fwWcx4ht1xHQ1a93ILM55Eg05w1oXGiNumlDmLJJAQKcDJ9Uoj%2bgaH8EyGVyy2vU45e9QnfybgSTMh%2bPAeNOR%2fiXPQ2KMAwK2AJ67KlHc7FnbaOqqeHFUKNil65zgsWDq2Qj6Wru8aPM57UIjXG7m2zLvtyt86kFH4ArR4rYOO3B0xiPEnOvJWQ4kDAb63Kr7Bo3Lh4oqcS%2bqqVSzQ4prt0R7lRPnHCwpVXsKu7FA6JvJCBguVM%2fAr4RpHGh3nEIEdVyY5nQcmsizFNP6Cq7s04%3d&seekable=0&x-dt-auth-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJvcHREYXRhIjoie1widXNlcklkXCI6XCI0MDQ2MDZhMS1mNmMxLTRjNTItYmNjNC1hNmNlNGVlY2M4ZTdcIixcIm1lcmNoYW50XCI6XCJoYm9ldXJvcGVcIixcInNlc3Npb25JZFwiOlwiMjFjZDM0OTctYTgzMS00ZjI3LTlhZmItZmNkZDY4OGZiOTVhXCJ9IiwiY3J0IjoiW3tcImFjY291bnRpbmdJZFwiOlwiZjkwYmMwMzQtNzdiNi1kNThkLWM4NTQtYjk4OWFkNDRjMjVlXCIsXCJhc3NldElkXCI6XCJDT01QXzFfLTEwMTQzNFwiLFwidmFyaWFudElkXCI6XCItMTAxNDM0XCIsXCJwcm9maWxlXCI6e1wicmVudGFsXCI6e1wiYWJzb2x1dGVFeHBpcmF0aW9uXCI6XCIyMDE4LTEwLTEyVDE4OjQwOjU5LjQ1OTUyMTdaXCIsXCJwbGF5RHVyYXRpb25cIjo5MjUyMTAwMH19LFwib3V0cHV0UHJvdGVjdGlvblwiOntcImRpZ2l0YWxcIjp0cnVlLFwiYW5hbG9ndWVcIjp0cnVlLFwiZW5mb3JjZVwiOmZhbHNlfX1dIiwiaWF0IjoxNTM5Mjc3MTM4LCJqdGkiOiJlZjhiYTQ1NTUxZWU0MjgxYjViNmUxYjI2MzUwNWQzYiJ9.tGmj3UmxzyRLBk1Y5DFPo_hdRlv5eadY7rSvHj3pnDJ5ULyatdYrT7YuT9GxZe46cHTXEx4HrFp2fws3DTnQqA
> 18:59:00.754 T:1531794304   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
> 18:59:00.755 T:1531794304   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
> 18:59:00.755 T:1531794304   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
> 18:59:00.757 T:1531794304   ERROR: CVideoPlayer::OpenInputStream - error opening [https://level3cdn.hbogo.eu/f90bc034-77b6-d58d-c854-b989ad44c25e_hbo/COMP/24016707_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_3400000.ism/Manifest]
> 18:59:00.757 T:1531794304  NOTICE: CVideoPlayer::OnExit()
> 18:59:00.904 T:1941346912 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (2.00s)

**Comment by mkoree** [comment]
Úgy látom másnak is van hasonló problémája: https://hup.hu/node/156409#comment-2263639

**Comment by iben12** [comment]
Erre van valami publikus megoldás? A hup-on csak annyi lett, h akit érdekel írjon privátot.

Aki megoldotta, megosztaná?

Köszi

**Comment by mkoree** [comment]
Igen, az elég gáz hogy nem írták be a megoldást, pláne hogy nem lehet csak úgy regelni az oldalra...

**Comment by Ch1p1** [comment]
a libwidevinecdm-ből kell egy új verziót feltenni, https://drive.google.com/open?id=1Qr0dQuEt_MZYRn_rHQ6JAgqaFjxTT7TQ nekem ezzel működik most a következő frissítésig. nekem raspbianra van felhúzva külön a kodi, így a ~/.kodi/cdm mappába kell bemásolni

**Comment by mkoree** [comment]
Köszi, működik! (Egyébként honnan szerezted?)

**Comment by iben12** [comment]
Ez működik! Köszi @Ch1p1 

A jegyzőkönyv kedvéért: honnan szerzed (buildeled, kiszeded, bármi) a megfelelő `libwidevinecdm.so`-t? 

Eddig nekem nem sikerült eljutnom, csak addig, hogy az kellene. Voltak ilyenek, hogy chromium-ot, vagy komplett chrome os-t kell buildelni hozzá...

*Setup: RPi2 + OSMC*

**Comment by Ch1p1** [comment]
Egy chromium imageből szedtem ki, nem kellett hozzá buildelni, szerencsére semmit. Innen van a chromium: https://cros-updates-serving.appspot.com/#speedy 

A teljesség kedvéért a chromium linket itt találtam: https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/35

**Comment by NH3CL** [comment]
Ismét előjött a hiba, viszont nem segit rajta a libwidevine frissités

`2019-08-19 13:53:16.969 T:1915414064  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.hbogohu/?url=https%3A%2F%2Fhuapi.hbogo.eu%2Fv5%2FContent%2FJson%2FHUN%2FCOMP%2F1f82d0c6-7714-057c-a410-2da027c8047b%2F&mode=5&name=A+SZOLG%C3%81L%C3%93L%C3%81NY+MES%C3%89JE+-+3.+%C3%89VAD+7.+R%C3%89SZ&cid=c2502f1f-38bb-9ef3-c7f3-8fdb65b8e30f&thumbnail=http://level3cdn.hbogo.eu/c2502f1f-38bb-9ef3-c7f3-8fdb65b8e30f_hbo/images/29367514.jpg
2019-08-19 13:53:17.128 T:1283711712  NOTICE: Creating InputStream
2019-08-19 13:53:19.627 T:1283711712   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 406
2019-08-19 13:53:19.627 T:1283711712   ERROR: CCurlFile::Open failed with code 406 for https://lic.drmtoday.com/license-proxy-widevine/cenc/:
2019-08-19 13:53:19.630 T:1283711712   ERROR: AddOnLog: InputStream Adaptive: License server returned failure
2019-08-19 13:53:19.630 T:1283711712   ERROR: AddOnLog: InputStream Adaptive: License update not successful (no keys)
2019-08-19 13:53:19.666 T:1283711712   ERROR: AddOnLog: InputStream Adaptive: Initialize failed (SingleSampleDecrypter)
2019-08-19 13:53:19.668 T:1283711712   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.hbogohu/?url=https%3A%2F%2Fhuapi.hbogo.eu%2Fv5%2FContent%2FJson%2FHUN%2FCOMP%2F1f82d0c6-7714-057c-a410-2da027c8047b%2F&mode=5&name=A+SZOLG%C3%81L%C3%93L%C3%81NY+MES%C3%89JE+-+3.+%C3%89VAD+7.+R%C3%89SZ&cid=c2502f1f-38bb-9ef3-c7f3-8fdb65b8e30f&thumbnail=http://level3cdn.hbogo.eu/c2502f1f-38bb-9ef3-c7f3-8fdb65b8e30f_hbo/images/29367514.jpg]
2019-08-19 13:53:19.668 T:1283711712  NOTICE: CVideoPlayer::OnExit()
2019-08-19 13:53:19.738 T:1915414064  NOTICE: CVideoPlayer::CloseFile()
2019-08-19 13:53:19.738 T:1915414064  NOTICE: VideoPlayer: waiting for threads to exit
2019-08-19 13:53:19.738 T:1915414064  NOTICE: VideoPlayer: finished waiting
2019-08-19 13:53:22.390 T:1556800224   ERROR: EXCEPTION: XBMC is not playing any media file
`

**Comment by biharitomi** [comment]
Nalam is elojott, persze miutan veletlenul elfelejtettem az `update`-re nyomni mikor ajanlotta a widevine-cdm frissiteset egy lejatszasnal.
Update-ltem az inputstream.helper-t, meg nem oldotta meg, torolni kellett a `~/.kodi/cdm` mappa tartalmat es ujra lejatszasra nyomni, hogy ujra felrakja a widevine lib-et. [Forras.](https://forum.kodi.tv/showthread.php?tid=346452&pid=2878793#pid2878793)

[Ha esetleg nincs eleg helyed, akkor itt talalsz megoldast, hogyan tudod a Chromium image-bol kibanyaszni a szukseges libeket.](https://help.vivaldi.com/article/raspberry-pi/#drm-and-flash)
